//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginInMVC4WithEF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Registration
    {
        public int UserId { get; set; }
        [Required]
        [EmailAddress]
        [StringLength(150)]
        [Display(Name = "Email Address: ")]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [StringLength(150, MinimumLength = 6)]
        [Display(Name = "Password: ")]
        public string Password { get; set; }


		[Required(ErrorMessage = "Confirm Password Required:")]
		[DataType(DataType.Password)]
		[Compare("Password", ErrorMessage = "Confirm not matched.")]
		[Display(Name = "Confirm password:")]
		[StringLength(30, ErrorMessage = "Less than 30 characters")]
        public string PasswordSalt { get; set; }

        [Required]
        [Display(Name = "First Name *")]
        public string FirstName { get; set; }

        [Required]        
        [Display(Name = "Last Name *")]
        public string LastName { get; set; } 
        public string UserType { get; set; }
        public System.DateTime CreatedDate { get; set; }

        public string IPAddress { get; set; }
        public Nullable<bool> IsNewsletter { get; set; }
		[Display(Name = "Suffix ")]
		public string Company { get; set; }

		[Display(Name = "Anonymous")]

		public bool IsActive { get; set; }


		

		public string Role { get; set; }
        public string SecurityAnswer { get; set; }
        public string SecurityQuestion { get; set; }
		[Required]
		[Display(Name = "phone number *")]
        public Nullable<int> IndustryId { get; set; }
        public string UserImage { get; set; }
		[Display(Name = "is active")]

		public Nullable<bool> Validated { get; set; }
		[Required]
		[Display(Name = "Emergency contact *")]

		public string UserIdGuid { get; set; }

		[Display(Name = "shirt size")]
		public string HowDidYouKnow { get; set; }
    }
}
